### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by fshadpey** [NIVeriStandAdd-Ons/GE-Reflective-Memory-Custom-Device-multiple-DMA-transfer#8]
Hi
I am having problem installing the CD. Here is what i have done:
- unzip the CD package
- install VeriStand Dev tools VIPC
- built all without any error: RefMem DMA Custom Device Project.lvproj 
- Copy the inf file to my PXI controller /ni-rt/system/ and reboot the target
- Copy RefMem DMA folder and .xml (under Built folder) to C:\Users\Public\Documents\National Instruments\NI VeriStand 2017\Custom Devices of my gateway

When i create a veristand project and open system explorer i see RefMem DMA under Custom Device tab, but, when selecting that i get an error page with the following message:

Broken page: 
C:\Users\Public\Documents\National Instruments\NI VeriStand 2017\Custom Devices\RefMem DMA\RefMem DMA Configuration.llb\RefMem DMA Main Page.vi

when i try to open broken vi from llb  directly from labview, it gives the following error:
Loading: 
     NationalInstruments.VeriStand.SystemDefinitionAPI.dll
Searching: 
     C:\Program Files (x86)\National Instruments\LabVIEW 2017\instr.lib\GE 5565 PIORC\Public\Utility

I appreciate any help in resolving this issue.
Thanks

**Comment by fshadpey** [comment]
Forgot to mention that i am using Labview and Veristand 2017.

**Comment by VincentRuault** [comment]
I worked off-line with customer.

**Comment by 3038814044** [comment]
Hello, I also encountered the same problem. I guess it is a build setting problem. The path setting inside is incorrect, but I changed some dependencies and still cannot solve the problem. Is your problem solved? How did you solve it?
