### ISSUE TITLE
VeriStand and Labview version problem

### ISSUE THREAD

**Issue by 3038814044** [NIVeriStandAdd-Ons/GE-Reflective-Memory-Custom-Device-multiple-DMA-transfer#9]
I am using VeriStand2020 and Labview2020 to develop the system. I would like to ask if this CD can also be supported in a higher version than 2017, thanks !

**Comment by tlemiere** [comment]
If it is not too late, the custom device can work with versions 2020. I have just pushed a new branch with some patches and the code LV code is in 2020 version.

**Comment by 3038814044** [comment]
Thank you !
